### PR TITLE
Always return ok or error tuple on connect

### LINKED ISSUE #177: TDS.Protocol fails to conform to DBConnection behavior resulting in a crash
On connect db connection can return values that do not conform to DBConnection behavior. Specifically, there are cases where `{0, _}` are returned from TDS.Protocol vs `{:error, _}` for some cases.

You can easily re-produce the behavior by connecting to a sql server instance (i.e., mssql/server in docker), stopping sql server, wait for failed connections, then start it back up. This results in a disconnect, and a return of `{0, _}` from TDS.Protocol on connect. 

This may indicate multiple problems in TDS.Protocol. That said, without the right shape to DBConnection, a hard crash ensues such that if a supervision tree is not tuned for indefinite failure, the application can be brought to a grinding halt.

### PR DESCRIPTION
**Pull request by starbelly**
Closes #177

### CODE REVIEW

File: lib/tds/protocol.ex [hunk 1]
```diff
@@ -364,19 +364,22 @@ defmodule Tds.Protocol do
...
-      end
-    else
+    case :gen_tcp.connect(host, port, sock_opts, timeout) do
+      {:ok, sock} ->
+         with {:ok, buffers} <- :inet.getopts(sock, [:sndbuf, :recbuf, :buffer]),
+              :ok <- :inet.setopts(sock, buffer: max_buf_size(buffers)),
+              {:ok, s} <- send_prelogin(%{s | sock: {:gen_tcp, sock}}) do
+           {:ok, s}
+         else
+           {:disconnect, exception, _state} ->
```
Comment (josevalim) [inline lib/tds/protocol.ex]:
```suggestion
           {_error_or_disconnect, exception, _state} ->
```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
